# Generated by Django 5.0.6 on 2024-07-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_comment_created_time_comment_updated_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
