# Generated by Django 5.0.6 on 2024-07-19 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_tag_tag_name"),
        ("myapp", "0004_remove_userdetail_pronouns"),
    ]

    operations = []
