# Generated by Django 5.0.6 on 2024-07-19 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_merge_20240719_0856"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
